name: Update README with a Random Quote

on:
  schedule:
    - cron: '0 */12 * * *' 
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch random quote
        run: |
          QUOTE=$(curl -s "http://api.quotable.io/quotes/random?tags=technology,famous-quotes" | jq -r '.[0].content + " - " + .[0].author')
          echo "Quote fetched: $QUOTE"
          echo "README before:"
          cat README.md
          sed -i "s|PLACEHOLDER_QUOTE|$QUOTE|g" README.md
          echo "README after:"
          cat README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated README with a new quote"
          git push
